import type { ShipGuardRule } from "@/lib/shipguard-engine/types";

export const shipGuardRules: ShipGuardRule[] = [
  {
    id: "product-landing-page",
    category: "product_readiness",
    title: "Landing page is missing",
    severity: "high",
    description: "The app should have a clear public landing page before launch.",
    detect: (ctx) => ctx.hasPath(/^app\/(page|home\/page)\.tsx$/),
    recommendedFix: "Add a launch-ready landing page with product positioning and a primary CTA.",
    builderPromptHint: "Inspect the app routes, then add a minimal landing page with headline, benefits, and CTA.",
  },
  {
    id: "product-pricing-page",
    category: "product_readiness",
    title: "Pricing page is missing",
    severity: "medium",
    description: "Paid SaaS products need a pricing path or explicit waitlist state.",
    detect: (ctx) => ctx.hasPath(/pricing\/page\.tsx$/),
    recommendedFix: "Create a pricing page or a clear placeholder explaining that billing is not active yet.",
    builderPromptHint: "Add a simple pricing route using existing card styles and no live Stripe calls.",
  },
  {
    id: "product-cta",
    category: "product_readiness",
    title: "Primary CTA is not visible",
    severity: "medium",
    description: "A launch page needs an obvious next action.",
    detect: (ctx) => ctx.hasContent(/get started|start trial|new project|sign up|book demo/i),
    recommendedFix: "Add a visible CTA that routes to signup, onboarding, or the dashboard.",
    builderPromptHint: "Find the main page and add one clear CTA using existing button styles.",
  },
  {
    id: "product-onboarding",
    category: "product_readiness",
    title: "Onboarding flow is missing",
    severity: "high",
    description: "New users need a guided first step after signup.",
    detect: (ctx) => ctx.hasPath(/onboarding\/page\.tsx$/),
    recommendedFix: "Add a minimal onboarding route with first-run guidance.",
    builderPromptHint: "Create a small onboarding page and link it from post-signup or dashboard empty state.",
  },
  {
    id: "product-dashboard",
    category: "product_readiness",
    title: "Dashboard route is missing",
    severity: "high",
    description: "A SaaS app needs a primary authenticated product surface.",
    detect: (ctx) => ctx.hasPath(/dashboard\/page\.tsx$/),
    recommendedFix: "Add a dashboard route with product status cards and empty states.",
    builderPromptHint: "Inspect existing layout components and add the smallest dashboard page needed.",
  },
  {
    id: "product-empty-states",
    category: "product_readiness",
    title: "Empty states are not documented",
    severity: "medium",
    description: "AI-built apps often fail when there is no user data yet.",
    detect: (ctx) => ctx.hasContent(/empty state|no .* yet|first-run|first run/i),
    recommendedFix: "Add empty states for dashboards, reports, and lists.",
    builderPromptHint: "Add concise empty state copy where lists or dashboards can render no data.",
  },
  {
    id: "product-support-path",
    category: "product_readiness",
    title: "Support or contact path is missing",
    severity: "low",
    description: "Users need a way to get help during launch.",
    detect: (ctx) => ctx.hasPath(/(support|contact)\/page\.tsx$/) || ctx.hasContent(/support@|contact@/i),
    recommendedFix: "Add a support link, contact page, or support email.",
    builderPromptHint: "Add a small support route or footer email without adding a ticketing system.",
  },
  {
    id: "auth-login",
    category: "auth_readiness",
    title: "Login route is missing",
    severity: "critical",
    description: "Users cannot access protected product areas without login.",
    detect: (ctx) => ctx.hasPath(/(login|sign-in)\/page\.tsx$/),
    recommendedFix: "Add a login route or link the app to the existing auth provider route.",
    builderPromptHint: "Inspect auth routes and add or normalize the login route only.",
  },
  {
    id: "auth-signup",
    category: "auth_readiness",
    title: "Signup route is missing",
    severity: "critical",
    description: "A launchable SaaS needs an account creation path.",
    detect: (ctx) => ctx.hasPath(/(signup|sign-up|register)\/page\.tsx$/),
    recommendedFix: "Add a signup route or make the waitlist state explicit.",
    builderPromptHint: "Create a minimal signup page using the existing auth UI pattern.",
  },
  {
    id: "auth-password-reset",
    category: "auth_readiness",
    title: "Password reset route is missing",
    severity: "medium",
    description: "Production users need a recovery path.",
    detect: (ctx) => ctx.hasPath(/(reset-password|forgot-password|password-reset)\/page\.tsx$/),
    recommendedFix: "Add a password reset route or documented provider handoff.",
    builderPromptHint: "Add a simple forgot password page; do not wire live auth if credentials are absent.",
  },
  {
    id: "auth-protected-routes",
    category: "auth_readiness",
    title: "Protected route handling is unclear",
    severity: "high",
    description: "Dashboard routes should not be public by accident.",
    detect: (ctx) => ctx.hasPath(/^middleware\.(ts|js)$/) || ctx.hasContent(/getServerSession|auth\(|requireAuth|session/i),
    recommendedFix: "Add middleware or route-level checks for authenticated areas.",
    builderPromptHint: "Inspect dashboard routes and add the smallest auth guard consistent with this app.",
  },
  {
    id: "auth-onboarding-redirect",
    category: "auth_readiness",
    title: "Onboarding redirect is missing",
    severity: "medium",
    description: "New users should land on an intentional first-run path.",
    detect: (ctx) => ctx.hasContent(/onboarding|firstRun|first_run|hasCompletedOnboarding/i),
    recommendedFix: "Add a simple onboarding completion flag or redirect plan.",
    builderPromptHint: "Add first-run redirect logic only where auth flow already routes users.",
  },
  {
    id: "billing-stripe-keys",
    category: "billing_readiness",
    title: "Stripe environment keys are not referenced",
    severity: "high",
    description: "Billing code should clearly document Stripe key requirements.",
    detect: (ctx) => ctx.hasContent(/STRIPE_/),
    recommendedFix: "Document required Stripe keys in .env.example and billing setup notes.",
    builderPromptHint: "Add Stripe env placeholders and setup notes without adding live secrets.",
  },
  {
    id: "billing-checkout-route",
    category: "billing_readiness",
    title: "Checkout route is missing",
    severity: "high",
    description: "Paid apps need a defined checkout entry point.",
    detect: (ctx) => ctx.hasPath(/(checkout|billing)\/(route|page)\.ts(x)?$/),
    recommendedFix: "Create a checkout or billing route placeholder with clear not-live copy.",
    builderPromptHint: "Add a checkout route placeholder and avoid live Stripe API calls.",
  },
  {
    id: "billing-webhook-route",
    category: "billing_readiness",
    title: "Stripe webhook route is missing",
    severity: "critical",
    description: "Subscriptions cannot be trusted without webhook handling.",
    detect: (ctx) => ctx.hasPath(/webhook.*route\.ts$/) || ctx.hasPath(/stripe\/webhooks\/route\.ts$/),
    recommendedFix: "Add a documented webhook route placeholder and verification TODO.",
    builderPromptHint: "Create a webhook route scaffold with explicit verification requirements, no live processing.",
  },
  {
    id: "billing-customer-portal",
    category: "billing_readiness",
    title: "Customer portal path is missing",
    severity: "medium",
    description: "Users need a way to manage subscription changes.",
    detect: (ctx) => ctx.hasContent(/customer portal|billing portal|portal session/i),
    recommendedFix: "Add a customer portal placeholder and cancellation management copy.",
    builderPromptHint: "Add portal UI copy only; do not wire Stripe portal yet.",
  },
  {
    id: "billing-plan-limits",
    category: "billing_readiness",
    title: "Plan limits are missing",
    severity: "medium",
    description: "Feature access should match the selected plan.",
    detect: (ctx) => ctx.hasContent(/plan limit|usage limit|subscription tier|trial/i),
    recommendedFix: "Document plan limits and trial behavior in the billing UI.",
    builderPromptHint: "Add visible plan limit copy and a simple data shape if one already exists.",
  },
  {
    id: "database-schema",
    category: "database_readiness",
    title: "Database schema or migrations are missing",
    severity: "high",
    description: "Production data structures should be reproducible.",
    detect: (ctx) => ctx.hasPath(/(schema|migration|migrations|supabase).*\.sql$/),
    recommendedFix: "Add schema or migration files for production tables.",
    builderPromptHint: "Create a minimal SQL schema scaffold; do not connect live Supabase.",
  },
  {
    id: "database-rls",
    category: "database_readiness",
    title: "RLS policies are missing",
    severity: "critical",
    description: "Supabase apps need row-level security before launch.",
    detect: (ctx) => ctx.hasPath(/rls.*\.sql$/) || ctx.hasContent(/enable row level security/i),
    recommendedFix: "Add owner-based RLS policies for user-owned tables.",
    builderPromptHint: "Add simple owner policies only; avoid team permissions for now.",
  },
  {
    id: "database-user-ownership",
    category: "database_readiness",
    title: "User ownership columns are missing",
    severity: "high",
    description: "User-owned data needs user_id or equivalent ownership columns.",
    detect: (ctx) => ctx.hasContent(/user_id|owner_id/),
    recommendedFix: "Add user_id ownership columns to user-scoped tables.",
    builderPromptHint: "Inspect SQL schema and add user ownership columns where appropriate.",
  },
  {
    id: "database-org-ownership",
    category: "database_readiness",
    title: "Organization ownership is not planned",
    severity: "low",
    description: "Future team support benefits from nullable organization ownership.",
    detect: (ctx) => ctx.hasContent(/organization_id|team_id/),
    recommendedFix: "Add nullable organization_id fields for future team support.",
    builderPromptHint: "Add nullable organization_id to schema files only if it matches existing patterns.",
  },
  {
    id: "database-updated-at",
    category: "database_readiness",
    title: "updated_at trigger support is missing",
    severity: "medium",
    description: "Production records should have reliable update timestamps.",
    detect: (ctx) => ctx.hasContent(/updated_at/) && ctx.hasContent(/trigger|set_updated_at/i),
    recommendedFix: "Add a minimal updated_at trigger function or documented timestamp strategy.",
    builderPromptHint: "Add a small updated_at trigger SQL helper if SQL scaffold already exists.",
  },
  {
    id: "security-env-leak",
    category: "security_readiness",
    title: "Possible environment secret leak",
    severity: "critical",
    description: "Private keys should never be committed into frontend code or examples.",
    detect: (ctx) => ctx.hasContent(/sk_live_|service_role=|SUPABASE_SERVICE_ROLE_KEY=.*[A-Za-z0-9]{12}/),
    passWhen: "not_detected",
    recommendedFix: "Remove committed secrets and replace them with placeholder names.",
    builderPromptHint: "Search for committed secrets, replace with placeholders, and do not print secret values.",
  },
  {
    id: "security-service-role-frontend",
    category: "security_readiness",
    title: "Service role may be exposed to frontend code",
    severity: "critical",
    description: "Supabase service role keys must stay server-only.",
    detect: (ctx) => ctx.hasContent(/NEXT_PUBLIC_.*SERVICE_ROLE|service_role/i) && ctx.hasPath(/components|app\/.*page\.tsx/),
    passWhen: "not_detected",
    recommendedFix: "Move service-role usage to server-only code and remove public exposure.",
    builderPromptHint: "Inspect public components and ensure service-role references are removed from client code.",
  },
  {
    id: "security-webhook-verification",
    category: "security_readiness",
    title: "Webhook verification is missing",
    severity: "high",
    description: "Payment webhooks must verify signatures.",
    detect: (ctx) => !ctx.hasPath(/webhook.*route\.ts$/) || ctx.hasContent(/constructEvent|signature|webhook secret/i),
    recommendedFix: "Add signature verification to webhook route scaffolds.",
    builderPromptHint: "If a webhook route exists, add explicit signature verification placeholder logic.",
  },
  {
    id: "security-rate-limits",
    category: "security_readiness",
    title: "Rate limiting is missing",
    severity: "medium",
    description: "Public routes and AI endpoints should have rate limits.",
    detect: (ctx) => ctx.hasContent(/rate limit|ratelimit|upstash|throttle/i),
    recommendedFix: "Add rate-limit placeholders or middleware notes for public and AI routes.",
    builderPromptHint: "Add minimal rate-limit structure or documented TODO near public routes.",
  },
  {
    id: "ai-provider-keys",
    category: "ai_readiness",
    title: "AI provider keys are not documented",
    severity: "medium",
    description: "AI features need explicit provider environment requirements.",
    detect: (ctx) => ctx.hasContent(/OPENAI_|ANTHROPIC_|AI_PROVIDER|GEMINI_/),
    recommendedFix: "Document AI provider keys without adding live values.",
    builderPromptHint: "Add AI env placeholders and setup copy only.",
  },
  {
    id: "ai-route",
    category: "ai_readiness",
    title: "AI route is missing",
    severity: "medium",
    description: "Apps with AI claims should have a clear server-side AI route boundary.",
    detect: (ctx) => ctx.hasPath(/(ai|chat|generate).*route\.ts$/),
    recommendedFix: "Add a server route placeholder for future AI calls.",
    builderPromptHint: "Create an AI route placeholder with no live model calls.",
  },
  {
    id: "ai-usage-limits",
    category: "ai_readiness",
    title: "AI usage limits are missing",
    severity: "high",
    description: "AI features can create runaway cost without usage controls.",
    detect: (ctx) => ctx.hasContent(/token|usage limit|cost tracking|ai usage|quota/i),
    recommendedFix: "Add usage-limit and token/cost tracking placeholders.",
    builderPromptHint: "Add usage limit UI/data placeholders; do not call a provider.",
  },
  {
    id: "ai-output-label",
    category: "ai_readiness",
    title: "AI output label is missing",
    severity: "low",
    description: "AI-generated content should be visibly labeled.",
    detect: (ctx) => ctx.hasContent(/AI Generated|AI-generated|generated by AI/i),
    recommendedFix: "Add an AI Generated badge near generated content.",
    builderPromptHint: "Add a small AI Generated badge using existing badge styles.",
  },
  {
    id: "deployment-build-script",
    category: "deployment_readiness",
    title: "Build script is missing",
    severity: "critical",
    description: "Vercel and CI need a production build command.",
    detect: (ctx) => ctx.hasPath(/^package\.json$/) && ctx.hasContent(/"build"\s*:/),
    recommendedFix: "Add a production build script.",
    builderPromptHint: "Inspect package.json and add a standard build script if missing.",
  },
  {
    id: "deployment-lint-script",
    category: "deployment_readiness",
    title: "Lint script is missing",
    severity: "medium",
    description: "Launch checks should include lint or type validation.",
    detect: (ctx) => ctx.hasPath(/^package\.json$/) && ctx.hasContent(/"lint"\s*:/),
    recommendedFix: "Add a lint script or document the validation command.",
    builderPromptHint: "Add the smallest lint script supported by the project.",
  },
  {
    id: "deployment-vercel",
    category: "deployment_readiness",
    title: "Vercel compatibility is unclear",
    severity: "low",
    description: "Next.js apps should declare or document Vercel compatibility.",
    detect: (ctx) => ctx.hasPath(/^next\.config\.(ts|js)$/) || ctx.hasPath(/^vercel\.json$/),
    recommendedFix: "Keep Next/Vercel config minimal and documented.",
    builderPromptHint: "Add deployment notes or minimal config only if the app already needs it.",
  },
  {
    id: "deployment-app-url",
    category: "deployment_readiness",
    title: "NEXT_PUBLIC_APP_URL is missing",
    severity: "medium",
    description: "Production redirects and webhooks often need the canonical app URL.",
    detect: (ctx) => ctx.hasContent(/NEXT_PUBLIC_APP_URL/),
    recommendedFix: "Add NEXT_PUBLIC_APP_URL to the env example and deployment checklist.",
    builderPromptHint: "Add app URL env documentation without setting a live production value.",
  },
  {
    id: "observability-error-logging",
    category: "observability_readiness",
    title: "Error logging is missing",
    severity: "medium",
    description: "Launch teams need visibility into runtime failures.",
    detect: (ctx) => ctx.hasContent(/Sentry|captureException|error logging|logger/i),
    recommendedFix: "Add a lightweight error logging placeholder or integration notes.",
    builderPromptHint: "Add a minimal logging wrapper or TODO; do not install new services unless requested.",
  },
  {
    id: "observability-health",
    category: "observability_readiness",
    title: "Health check route is missing",
    severity: "low",
    description: "A health route helps verify deployments quickly.",
    detect: (ctx) => ctx.hasPath(/(health|status)\/route\.ts$/),
    recommendedFix: "Add a simple health check route.",
    builderPromptHint: "Create a tiny /api/health route that returns a static healthy response.",
  },
  {
    id: "observability-payment-logs",
    category: "observability_readiness",
    title: "Payment event logs are missing",
    severity: "medium",
    description: "Billing launch issues are hard to debug without event logs.",
    detect: (ctx) => ctx.hasContent(/payment event|stripe event|audit log/i),
    recommendedFix: "Add payment event logging notes or placeholders.",
    builderPromptHint: "Add explicit payment event logging TODO near webhook scaffolds.",
  },
  {
    id: "observability-ai-logs",
    category: "observability_readiness",
    title: "AI usage logs are missing",
    severity: "medium",
    description: "AI cost and quality issues need usage logs.",
    detect: (ctx) => ctx.hasContent(/ai usage log|token log|prompt log/i),
    recommendedFix: "Add AI usage logging placeholders.",
    builderPromptHint: "Add AI usage logging data shape or TODO without calling a provider.",
  },
  {
    id: "legal-privacy",
    category: "legal_trust_readiness",
    title: "Privacy policy is missing",
    severity: "high",
    description: "Production SaaS apps need privacy terms before launch.",
    detect: (ctx) => ctx.hasPath(/privacy\/page\.tsx$/),
    recommendedFix: "Add a privacy policy placeholder reviewed before launch.",
    builderPromptHint: "Add a simple privacy page placeholder, clearly marked for legal review.",
  },
  {
    id: "legal-terms",
    category: "legal_trust_readiness",
    title: "Terms page is missing",
    severity: "high",
    description: "Users need terms before account creation and billing.",
    detect: (ctx) => ctx.hasPath(/terms\/page\.tsx$/),
    recommendedFix: "Add a terms page placeholder reviewed before launch.",
    builderPromptHint: "Add a simple terms page placeholder, clearly marked for legal review.",
  },
  {
    id: "legal-refunds",
    category: "legal_trust_readiness",
    title: "Refund or cancellation language is missing",
    severity: "medium",
    description: "Paid SaaS needs clear cancellation expectations.",
    detect: (ctx) => ctx.hasContent(/refund|cancel subscription|cancellation/i),
    recommendedFix: "Add refund and cancellation language to billing/support pages.",
    builderPromptHint: "Add concise cancellation copy to billing and support surfaces.",
  },
  {
    id: "legal-ai-disclaimer",
    category: "legal_trust_readiness",
    title: "AI disclaimer is missing",
    severity: "low",
    description: "Apps with AI output should explain AI limitations.",
    detect: (ctx) => ctx.hasContent(/AI disclaimer|AI output|generated content may/i),
    recommendedFix: "Add AI disclaimer copy near generated content or legal pages.",
    builderPromptHint: "Add a short AI disclaimer using existing copy style.",
  },
  {
    id: "success-welcome-guide",
    category: "customer_success_readiness",
    title: "Welcome or onboarding guide is missing",
    severity: "medium",
    description: "Users should understand what to do first.",
    detect: (ctx) => ctx.hasContent(/welcome|getting started|onboarding guide/i),
    recommendedFix: "Add a welcome guide or first-run checklist.",
    builderPromptHint: "Add concise first-run guidance in the dashboard or onboarding route.",
  },
  {
    id: "success-demo-data",
    category: "customer_success_readiness",
    title: "Demo data path is missing",
    severity: "low",
    description: "Demo data helps new users understand the product faster.",
    detect: (ctx) => ctx.hasContent(/demo data|sample data|example project/i),
    recommendedFix: "Add demo data copy or sample state for first-run users.",
    builderPromptHint: "Add a mock demo data option or explanatory sample state.",
  },
  {
    id: "success-help-docs",
    category: "customer_success_readiness",
    title: "Help docs or FAQ are missing",
    severity: "medium",
    description: "Launch users need self-serve answers.",
    detect: (ctx) => ctx.hasPath(/(help|docs|faq)\/page\.tsx$/),
    recommendedFix: "Add a minimal FAQ or help page.",
    builderPromptHint: "Create a short FAQ page with launch-critical questions only.",
  },
  {
    id: "success-upgrade-prompts",
    category: "customer_success_readiness",
    title: "Upgrade prompts are missing",
    severity: "low",
    description: "Users should understand when paid plans matter.",
    detect: (ctx) => ctx.hasContent(/upgrade|plan limit|unlock/i),
    recommendedFix: "Add upgrade prompts around limited features.",
    builderPromptHint: "Add upgrade copy to existing plan or empty-state surfaces.",
  },
];
